#!/bin/bash

python caption.py --img="images/$1.jpg" --model="pretrained/BEST_checkpoint_coco_5_cap_per_img_5_min_word_freq.pth.tar" --word_map="pretrained/WORDMAP_coco_5_cap_per_img_5_min_word_freq.json" --beam_size=5
